export const ErrorCodes = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Products / carts
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_NOT_OPEN: 'CART_NOT_OPEN',
  CART_EMPTY: 'CART_EMPTY',

  // Checkout
  INSUFFICIENT_INVENTORY: 'INSUFFICIENT_INVENTORY',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_MISMATCH: 'IDEMPOTENCY_KEY_MISMATCH',

  // Orders / coupons
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  COUPON_ALREADY_REDEEMED: 'COUPON_ALREADY_REDEEMED',
  NO_ELIGIBLE_MILESTONE: 'NO_ELIGIBLE_MILESTONE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
